---
- name: Install epel repo
  yum: pkg={{item}}
  with_items:
    - epel-release
  when: ansible_os_family == "RedHat"

- name: Enable epel repositories
  ini_file: dest=/etc/yum.repos.d/epel.repo
            section={{ item }}
            option=enabled
            value=1
  when: ansible_os_family == "RedHat"
  with_items: enabled_epel_repositories

- name: Disable epel repositories
  ini_file: dest=/etc/yum.repos.d/epel.repo
            section={{ item }}
            option=enabled
            value=0
  when: ansible_os_family == "RedHat"
  with_items: disabled_epel_repositories

- name: Enable epel-testing repositories
  ini_file: dest=/etc/yum.repos.d/epel-testing.repo
            section={{ item }}
            option=enabled
            value=1
  when: ansible_os_family == "RedHat"
  with_items: enabled_epeltesting_repositories

- name: Disable epel-testing repositories
  ini_file: dest=/etc/yum.repos.d/epel-testing.repo
            section={{ item }}
            option=enabled
            value=0
  when: ansible_os_family == "RedHat"
  with_items: disabled_epeltesting_repositories