---
- name: Install remi repo for Distro-Version 6
  yum: pkg={{item}}
  with_items:
    - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
  when: ansible_os_family == "RedHat" and ansible_distribution_version.split(".")[0] == '6'

- name: Install remi repo for Distro-Version 7
  yum: pkg={{item}}
  with_items:
    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
  when: ansible_os_family == "RedHat" and ansible_distribution_version.split(".")[0] == '7'

- name: Enable remi repositories
  ini_file: dest=/etc/yum.repos.d/remi.repo
            section={{ item }}
            option=enabled
            value=1
  when: ansible_os_family == "RedHat"
  with_items: enabled_remi_repositories

- name: Disable remi repositories
  ini_file: dest=/etc/yum.repos.d/remi.repo
            section={{ item }}
            option=enabled
            value=0
  when: ansible_os_family == "RedHat"
  with_items: disabled_remi_repositories
